# Generated by Django 5.1.1 on 2024-10-05 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Nome da Empresa')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('cpf_cnpj', models.CharField(max_length=20, unique=True, verbose_name='CPF/CNPJ')),
                ('state_register_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Inscrição Estadual')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('field_area', models.CharField(blank=True, max_length=255, null=True, verbose_name='Área de Atuação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('modified_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Modificação')),
            ],
        ),
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('modified_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Modificação')),
            ],
        ),
        migrations.CreateModel(
            name='OrderBatch',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('germination', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Germinação')),
                ('purity', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Pureza')),
                ('observation', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('approved', models.BooleanField(default=False, verbose_name='Aprovado')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade')),
                ('premium', models.BooleanField(default=False, verbose_name='Premium')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('modified_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Modificação')),
            ],
        ),
        migrations.CreateModel(
            name='Packing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('unity', models.CharField(max_length=50, verbose_name='Unidade')),
                ('volume', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Volume')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('modified_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Modificação')),
            ],
        ),
        migrations.CreateModel(
            name='Tsi',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('receipt', models.TextField(blank=True, null=True, verbose_name='Receita')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('modified_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Modificação')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='Nome de usuário')),
                ('password', models.CharField(max_length=255, verbose_name='Senha')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
        ),
        migrations.CreateModel(
            name='ClientAddress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255, verbose_name='Rua')),
                ('number', models.CharField(max_length=10, verbose_name='Número')),
                ('neighborhood', models.CharField(max_length=255, verbose_name='Bairro')),
                ('city', models.CharField(max_length=255, verbose_name='Cidade')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('complement', models.CharField(blank=True, max_length=255, null=True, verbose_name='Complemento')),
                ('state_abbreviation', models.CharField(max_length=2, verbose_name='UF')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seeds.client', verbose_name='Cliente')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='address_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seeds.clientaddress', verbose_name='Endereço'),
        ),
        migrations.CreateModel(
            name='ClientContact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('modified_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Modificação')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seeds.client', verbose_name='Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='ClientMail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('responsible', models.CharField(max_length=255, verbose_name='Responsável')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('modified_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Modificação')),
                ('contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seeds.clientcontact', verbose_name='Contato')),
            ],
        ),
        migrations.CreateModel(
            name='ClientNegotiation',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50, verbose_name='Status')),
                ('observation', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Data de Modificação')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seeds.client', verbose_name='Cliente')),
                ('responsible_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seeds.user', verbose_name='Responsável')),
            ],
        ),
        migrations.CreateModel(
            name='ClientOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('status', models.CharField(max_length=50, verbose_name='Status')),
                ('shipping', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Frete')),
                ('payment_method', models.CharField(max_length=50, verbose_name='Forma de Pagamento')),
                ('observation', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('payment_details', models.TextField(blank=True, null=True, verbose_name='Detalhes do Pagamento')),
                ('cancelling_observation', models.TextField(blank=True, null=True, verbose_name='Observação de Cancelamento')),
                ('negotiation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seeds.clientnegotiation', verbose_name='Negociação')),
            ],
        ),
        migrations.CreateModel(
            name='ClientPhone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Número de Telefone')),
                ('type', models.CharField(max_length=50, verbose_name='Tipo')),
                ('responsible', models.CharField(max_length=255, verbose_name='Responsável')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('modified_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Modificação')),
                ('contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seeds.clientcontact', verbose_name='Contato')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=30, max_digits=65, verbose_name='Quantidade')),
                ('unit_price', models.DecimalField(decimal_places=30, max_digits=65, verbose_name='Preço Unitário')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('packing_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID da Embalagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('modified_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Modificação')),
                ('current_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seeds.orderbatch', verbose_name='Lote Atual')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seeds.clientorder', verbose_name='Pedido')),
                ('custom_tsi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seeds.tsi', verbose_name='TSI Personalizado')),
            ],
        ),
        migrations.CreateModel(
            name='OrderBatchPacking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('batch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seeds.orderbatch', verbose_name='Lote')),
                ('packing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seeds.packing', verbose_name='Embalagem')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoLote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade Solicitada')),
                ('opened', models.BooleanField(default=True, verbose_name='Aberto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Data de Modificação')),
                ('batch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seeds.orderbatch', verbose_name='Lote')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seeds.orderitems', verbose_name='Item')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seeds.clientorder', verbose_name='Pedido')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seeds.user', verbose_name='Usuário'),
        ),
        migrations.CreateModel(
            name='UserCheckIn',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seeds.client', verbose_name='Cliente')),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seeds.user', verbose_name='Vendedor')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('works_at', models.CharField(max_length=255, verbose_name='Local de Trabalho')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('registration', models.CharField(max_length=255, verbose_name='Registro / Matrícula')),
                ('cargo', models.CharField(max_length=255, verbose_name='Cargo')),
                ('avatar_url', models.URLField(max_length=500, verbose_name='URL do Avatar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seeds.user', verbose_name='Usuário')),
            ],
        ),
        migrations.CreateModel(
            name='Variety',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('observation', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('disabled_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Desativação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('modified_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Modificação')),
                ('culture_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seeds.culture', verbose_name='Cultura')),
            ],
        ),
        migrations.AddField(
            model_name='orderbatch',
            name='variety_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seeds.variety', verbose_name='Variedade'),
        ),
    ]
