# Generated by Django 5.1.1 on 2024-10-05 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='item_culture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seeds.culture', verbose_name='Cultura'),
        ),
        migrations.AddField(
            model_name='orderitems',
            name='item_variety',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seeds.variety', verbose_name='Variedade'),
        ),
        migrations.RenameModel(
            old_name='PedidoLote',
            new_name='OrderBatchRelation',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('status', models.CharField(max_length=50, verbose_name='Status')),
                ('shipping', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Frete')),
                ('payment_method', models.CharField(max_length=50, verbose_name='Forma de Pagamento')),
                ('observation', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('payment_details', models.TextField(blank=True, null=True, verbose_name='Detalhes do Pagamento')),
                ('cancelling_observation', models.TextField(blank=True, null=True, verbose_name='Observação de Cancelamento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('modified_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Modificação')),
                ('negotiation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seeds.clientnegotiation', verbose_name='Negociação')),
            ],
        ),
        migrations.AlterField(
            model_name='orderbatchrelation',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seeds.order', verbose_name='Pedido'),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seeds.order', verbose_name='Pedido'),
        ),
        migrations.DeleteModel(
            name='ClientOrder',
        ),
    ]
