# Generated by Django 5.1.1 on 2024-10-05 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeds', '0002_orderitems_item_culture_orderitems_item_variety_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='company_name',
            field=models.CharField(max_length=255, verbose_name='Razão Social'),
        ),
        migrations.AlterField(
            model_name='client',
            name='field_area',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Área de Campo'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome Fantasia'),
        ),
    ]
