# Generated by Django 5.1.1 on 2024-10-05 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeds', '0003_alter_client_company_name_alter_client_field_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='field_area',
            field=models.IntegerField(blank=True, max_length=255, null=True, verbose_name='Área de Campo (Ha)'),
        ),
    ]
