# Generated by Django 5.1.1 on 2024-10-05 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeds', '0005_alter_client_field_area_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCargo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
        ),
        migrations.RenameField(
            model_name='client',
            old_name='name',
            new_name='fantasy_name',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seeds.usercargo', verbose_name='Cargo'),
        ),
    ]
