# Generated by Django 5.1.1 on 2024-10-05 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seeds', '0007_alter_userprofile_avatar_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='clientaddress',
            options={'verbose_name': 'Endereço', 'verbose_name_plural': 'Endereços'},
        ),
        migrations.AlterModelOptions(
            name='clientcontact',
            options={'verbose_name': 'Contato de Cliente', 'verbose_name_plural': 'Contatos de Clientes'},
        ),
        migrations.AlterModelOptions(
            name='clientmail',
            options={'verbose_name': 'E-mail', 'verbose_name_plural': 'E-mails'},
        ),
        migrations.AlterModelOptions(
            name='clientnegotiation',
            options={'verbose_name': 'Negociação', 'verbose_name_plural': 'Negociações'},
        ),
        migrations.AlterModelOptions(
            name='clientphone',
            options={'verbose_name': 'Telefone', 'verbose_name_plural': 'Telefones'},
        ),
        migrations.AlterModelOptions(
            name='culture',
            options={'verbose_name': 'Cultura', 'verbose_name_plural': 'Culturas'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='orderbatch',
            options={'verbose_name': 'Lote', 'verbose_name_plural': 'Lotes'},
        ),
        migrations.AlterModelOptions(
            name='orderbatchpacking',
            options={'verbose_name': 'Embalagem por Lote', 'verbose_name_plural': 'Embalagens por Lote'},
        ),
        migrations.AlterModelOptions(
            name='orderbatchrelation',
            options={'verbose_name': 'Relação Pedido / Lote', 'verbose_name_plural': 'Relações Pedido / Lote'},
        ),
        migrations.AlterModelOptions(
            name='orderitems',
            options={'verbose_name': 'Item do Pedido', 'verbose_name_plural': 'Itens do Pedido'},
        ),
        migrations.AlterModelOptions(
            name='packing',
            options={'verbose_name': 'Embalagem', 'verbose_name_plural': 'Embalagens'},
        ),
        migrations.AlterModelOptions(
            name='tsi',
            options={'verbose_name': 'Tratamento de Semente', 'verbose_name_plural': 'Tratamento de Sementes'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.AlterModelOptions(
            name='usercargo',
            options={'verbose_name': 'Cargo', 'verbose_name_plural': 'Cargos'},
        ),
        migrations.AlterModelOptions(
            name='usercheckin',
            options={'verbose_name': 'Check-In', 'verbose_name_plural': 'Check-Ins'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Perfil de Usuário', 'verbose_name_plural': 'Perfis de Usuário'},
        ),
        migrations.AlterModelOptions(
            name='variety',
            options={'verbose_name': 'Variedade', 'verbose_name_plural': 'Variedades'},
        ),
    ]
