# Generated by Django 5.1.1 on 2024-10-05 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeds', '0008_alter_client_options_alter_clientaddress_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbatch',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
