# Generated by Django 5.1.1 on 2024-10-05 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeds', '0009_alter_orderbatch_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientnegotiation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tsi',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usercheckin',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
