# Generated by Django 5.1.1 on 2024-10-06 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeds', '0011_alter_variety_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='NegotiationStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Status da Negociação',
                'verbose_name_plural': 'Status das Negociações',
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Status do Pedido',
                'verbose_name_plural': 'Status dos Pedidos',
            },
        ),
        migrations.RemoveField(
            model_name='clientnegotiation',
            name='status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='clientnegotiation',
            name='negotiation_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seeds.negotiationstatus', verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seeds.orderstatus', verbose_name='Status'),
        ),
    ]
