# Generated by Django 5.1.1 on 2024-10-06 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeds', '0012_negotiationstatus_orderstatus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderShipping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Frete',
                'verbose_name_plural': 'Fretes',
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seeds.ordershipping', verbose_name='Frete'),
        ),
    ]
