# Generated by Django 5.1.1 on 2024-10-06 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeds', '0014_paymentmethods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seeds.paymentmethods', verbose_name='Forma de Pagamento'),
        ),
    ]
