# Generated by Django 5.1.1 on 2024-10-06 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeds', '0015_alter_order_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='packing_id',
        ),
        migrations.AddField(
            model_name='orderitems',
            name='packing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seeds.packing', verbose_name='Embalagem'),
        ),
    ]
