# Generated by Django 5.1.1 on 2024-10-06 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seeds', '0016_remove_orderitems_packing_id_orderitems_packing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitems',
            old_name='packing',
            new_name='packing_id',
        ),
    ]
